DROP TABLE Users CASCADE;

DROP TABLE Posts CASCADE;

DROP TABLE Votes CASCADE;

CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) UNIQUE,
  name VARCHAR(100),
  facebookID VARCHAR(100)
);

CREATE TABLE Posts (
  id SERIAL PRIMARY KEY,
  userID INTEGER,
  photo VARCHAR(200),
  item_name VARCHAR(100),
  item_type VARCHAR(200),
  comment VARCHAR(500),

  FOREIGN KEY (userID) REFERENCES Users(id)
);

CREATE TABLE Votes (
  id SERIAL PRIMARY KEY,
  voterID INTEGER,
  postID INTEGER,
  vote INTEGER,

  FOREIGN KEY (voterID) REFERENCES Users(id),
  FOREIGN KEY (postID) REFERENCES Posts(id)
);
